### ISSUE TITLE
Error,please i want answer for this

### ISSUE THREAD

**Issue by chathurip** [aksh4y/Papers#1]
When running app.py i get this type of eroor

AttributeError: module 'sys' has no attribute 'setdefaultencoding'

How i fix this?????

**Comment by chathurip** [comment]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4195: character maps to <undefined>

i want fix this one,how can i do this?

**Comment by ghost** [comment]
@chathurip You are probably using Python 3 for which you can skip this line of code. Since Python 3 is by default encoded in UTF-8, the line doesn't make sense. I used Python 2.x for which it was useful.
For your second issue as well it seems to be an issue related to UTF-8. You can try using 
`file = open(filename, encoding="utf8")`
You could also just try running the project with Python 2.7 to avoid further workarounds.
